### ISSUE TITLE
java.lang.ExceptionInInitializerError When calling from Jython

### ISSUE THREAD

**Issue by muh182** [jythontools/jython#100]
I have a Jython code that calls a series of Java classes.  I face the following error when I try to create a new object for one of the classes :

```
from demo import TestUtilityOntologyNYC
ontVar = TestUtilityOntologyNYC()
```

I get this error:
```
	at demo.AbstractOntologyModel.<init>(AbstractOntologyModel.java:80)
	at demo.TestUtilityOntologyNYC.<init>(TestUtilityOntologyNYC.java:101)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)
java.lang.ExceptionInInitializerError: java.lang.ExceptionInInitializerError
```
The code works fine as a standalone Java. I only get some warnings 
```
log4j:WARN No appenders could be found for logger (Jena).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
I am using Jython 2.7.1  and 
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
 and my OS is MacOs X 10.13.2

**Comment by jeff5** [comment]
Dealt with in discussion of #99
