### ISSUE TITLE
Compiled jython-dev.jar is mute

### ISSUE THREAD

**Issue by RichardDally** [jythontools/jython#144]
I succeeded to compile Jython 2.7.1 but unfortunately produced binary doesn't work even tho build has been successful.
I'm executing it and it says nothing.
```
C:\Repositories\jython\dist>jython-dev.jar --help

C:\Repositories\jython\dist>jython-dev.jar -m pip

C:\Repositories\jython\dist>jython-dev.jar

C:\Repositories\jython\dist>
```

It's a bit better with jython.exe for help but not for all other stuff :
```
C:\Repositories\jython\dist\bin>jython.exe --help
usage: jython [option] ... [-c cmd | -m mod | file | -] [arg] ...
Options and arguments:
-B       : don't write bytecode files on import
-c cmd   : program passed in as string (terminates option list)
-Dprop=v : Set the property `prop' to value `v'
[...]
```

Am I missing some step ?

Windows 10, tag v2.7.1, JDK 1.8.0_101

```
C:\jdk-windows-1.8.0_101\bin>java.exe -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

```

```
C:\Repositories\jython>ant
Buildfile: C:\Repositories\jython\build.xml

init:

needed-check:

clean-if-antlr-needed:

init:

clean-checkout-dir:

clean:

prepare-output:
    [mkdir] Created dir: C:\Repositories\jython\build\classes
    [mkdir] Created dir: C:\Repositories\jython\build\gensrc\org\python\antlr
    [mkdir] Created dir: C:\Repositories\jython\build\exposed

antlr_gen:
     [java] warning(105): C:\Repositories\jython\grammar\Python.g:1278:10: no lexer rule corresponding to token: DEDENT
     [java] warning(105): C:\Repositories\jython\grammar\Python.g:1271:15: no lexer rule corresponding to token: INDENT
     [java] warning(200): C:\Repositories\jython\grammar\Python.g:1986:59: Decision can match input such as "COMMA BACKQUOTE" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] warning(200): C:\Repositories\jython\grammar\Python.g:1986:62: Decision can match input such as "COMMA" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] error(10):  internal error: Can't get property indirectDelegates using method get/isIndirectDelegates from org.antlr.tool.Grammar instance : java.lang.NullPointerException
     [java] java.util.Objects.requireNonNull(Unknown Source)
     [java] java.util.ArrayList.removeAll(Unknown Source)
     [java] org.antlr.tool.CompositeGrammar.getIndirectDelegates(CompositeGrammar.java:222)
     [java] org.antlr.tool.Grammar.getIndirectDelegates(Grammar.java:2620)
     [java] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     [java] sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     [java] java.lang.reflect.Method.invoke(Unknown Source)
     [java] org.antlr.stringtemplate.language.ASTExpr.invokeMethod(ASTExpr.java:563)
     [java] org.antlr.stringtemplate.language.ASTExpr.rawGetObjectProperty(ASTExpr.java:514)
     [java] org.antlr.stringtemplate.language.ASTExpr.getObjectProperty(ASTExpr.java:416)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.attribute(ActionEvaluator.java:351)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.expr(ActionEvaluator.java:136)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.templateApplication(ActionEvaluator.java:216)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.expr(ActionEvaluator.java:126)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:84)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:148)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:722)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:659)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:148)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:722)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:659)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:148)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:722)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:659)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:148)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:722)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:659)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:148)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
     [java] org.antlr.codegen.CodeGenerator.write(CodeGenerator.java:1278)
     [java] org.antlr.codegen.Target.genRecognizerFile(Target.java:94)
     [java] org.antlr.codegen.CodeGenerator.genRecognizer(CodeGenerator.java:463)
     [java] org.antlr.Tool.generateRecognizer(Tool.java:607)
     [java] org.antlr.Tool.process(Tool.java:429)
     [java] org.antlr.Tool.main(Tool.java:91)
     [java] warning(200): C:\Repositories\jython\grammar\Python.g:2389:7: Decision can match input such as "'"'" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] warning(200): C:\Repositories\jython\grammar\Python.g:2395:7: Decision can match input such as "'\''" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] warning(200): C:\Repositories\jython\grammar\Python.g:2408:37: Decision can match input such as "{'\t', ' '}" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] Semantic predicates were present but were hidden by actions.
     [java] warning(105): C:\Repositories\jython\grammar\PythonPartial.g:562:17: no lexer rule corresponding to token: INDENT
     [java] warning(105): C:\Repositories\jython\grammar\PythonPartial.g:702:7: no lexer rule corresponding to token: TRAILBACKSLASH
     [java] warning(105): C:\Repositories\jython\grammar\PythonPartial.g:562:33: no lexer rule corresponding to token: DEDENT
     [java] warning(105): C:\Repositories\jython\grammar\PythonPartial.g:561:18: no lexer rule corresponding to token: DEDENT
     [java] warning(105): C:\Repositories\jython\grammar\PythonPartial.g:740:19: no lexer rule corresponding to token: TRAILBACKSLASH
     [java] warning(200): C:\Repositories\jython\grammar\PythonPartial.g:175:27: Decision can match input such as "NEWLINE" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] warning(200): C:\Repositories\jython\grammar\PythonPartial.g:250:7: Decision can match input such as "AT" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] warning(200): C:\Repositories\jython\grammar\PythonPartial.g:815:39: Decision can match input such as "COMMA BACKQUOTE" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] warning(200): C:\Repositories\jython\grammar\PythonPartial.g:815:42: Decision can match input such as "COMMA" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] error(10):  internal error: Can't get property indirectDelegates using method get/isIndirectDelegates from org.antlr.tool.Grammar instance : java.lang.NullPointerException
     [java] java.util.Objects.requireNonNull(Unknown Source)
     [java] java.util.ArrayList.removeAll(Unknown Source)
     [java] org.antlr.tool.CompositeGrammar.getIndirectDelegates(CompositeGrammar.java:222)
     [java] org.antlr.tool.Grammar.getIndirectDelegates(Grammar.java:2620)
     [java] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     [java] sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     [java] java.lang.reflect.Method.invoke(Unknown Source)
     [java] org.antlr.stringtemplate.language.ASTExpr.invokeMethod(ASTExpr.java:563)
     [java] org.antlr.stringtemplate.language.ASTExpr.rawGetObjectProperty(ASTExpr.java:514)
     [java] org.antlr.stringtemplate.language.ASTExpr.getObjectProperty(ASTExpr.java:416)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.attribute(ActionEvaluator.java:351)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.expr(ActionEvaluator.java:136)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.templateApplication(ActionEvaluator.java:216)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.expr(ActionEvaluator.java:126)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:84)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:148)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:722)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:659)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:148)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:722)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:659)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:148)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:722)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:659)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:148)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:700)
     [java] org.antlr.codegen.CodeGenerator.write(CodeGenerator.java:1278)
     [java] org.antlr.codegen.Target.genRecognizerFile(Target.java:94)
     [java] org.antlr.codegen.CodeGenerator.genRecognizer(CodeGenerator.java:463)
     [java] org.antlr.Tool.generateRecognizer(Tool.java:607)
     [java] org.antlr.Tool.process(Tool.java:429)
     [java] org.antlr.Tool.main(Tool.java:91)
     [java] warning(200): C:\Repositories\jython\grammar\PythonPartial.g:1085:38: Decision can match input such as "'\\''\n'{'\t', ' '}'#''\\''\n'" using multiple alternatives: 1, 3
     [java] As a result, alternative(s) 3 were disabled for that input
     [java] warning(200): C:\Repositories\jython\grammar\PythonPartial.g:1085:38: Decision can match input such as "'\\''\n'{'\t', ' '}'#''\\''\r''\n'" using multiple alternatives: 1, 3
     [java] As a result, alternative(s) 3 were disabled for that input
     [java] warning(200): C:\Repositories\jython\grammar\PythonPartial.g:1086:40: Decision can match input such as "'\\''\n'{'\t', ' '}'#''\\''\n'" using multiple alternatives: 1, 3
     [java] As a result, alternative(s) 3 were disabled for that input
     [java] warning(200): C:\Repositories\jython\grammar\PythonPartial.g:1086:40: Decision can match input such as "'\\''\n'{'\t', ' '}'#''\\''\r''\n'" using multiple alternatives: 1, 3
     [java] As a result, alternative(s) 3 were disabled for that input
     [java] warning(200): C:\Repositories\jython\grammar\PythonPartial.g:1094:7: Decision can match input such as "'"'" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] warning(200): C:\Repositories\jython\grammar\PythonPartial.g:1100:7: Decision can match input such as "'\''" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] warning(200): C:\Repositories\jython\grammar\PythonPartial.g:1116:37: Decision can match input such as "{'\t', ' '}" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] Semantic predicates were present but were hidden by actions.
     [java] Java Result: 1

check-hg:

hg-branch:

hg-tag:

hg-version:

hg-id:

brand-version:
    [mkdir] Created dir: C:\Repositories\jython\build\classes\org\python

compile:
    [javac] C:\Repositories\jython\build.xml:469: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 882 source files to C:\Repositories\jython\build\classes
    [javac] C:\Repositories\jython\src\org\python\expose\generate\NewExposer.java:53: warning: [deprecation] visitMethodInsn(int,String,String,String) in MethodVisitor has been deprecated
    [javac]         mv.visitMethodInsn(INVOKESTATIC, onType.getInternalName(), name, NEW_DESCRIPTOR);
    [javac]           ^
    [javac] C:\Repositories\jython\src\org\python\modules\jffi\SkinnyMethodAdapter.java:156: warning: [deprecation] visitMethodInsn(int,String,String,String) in MethodVisitor has been deprecated
    [javac]         getMethodVisitor().visitMethodInsn(INVOKESTATIC, arg1, arg2, arg3);
    [javac]                           ^
    [javac] C:\Repositories\jython\src\org\python\modules\jffi\SkinnyMethodAdapter.java:160: warning: [deprecation] visitMethodInsn(int,String,String,String) in MethodVisitor has been deprecated
    [javac]         getMethodVisitor().visitMethodInsn(INVOKESPECIAL, arg1, arg2, arg3);
    [javac]                           ^
    [javac] C:\Repositories\jython\src\org\python\modules\jffi\SkinnyMethodAdapter.java:164: warning: [deprecation] visitMethodInsn(int,String,String,String) in MethodVisitor has been deprecated
    [javac]         getMethodVisitor().visitMethodInsn(INVOKEVIRTUAL, arg1, arg2, arg3);
    [javac]                           ^
    [javac] C:\Repositories\jython\src\org\python\modules\jffi\SkinnyMethodAdapter.java:168: warning: [deprecation] visitMethodInsn(int,String,String,String) in MethodVisitor has been deprecated
    [javac]         getMethodVisitor().visitMethodInsn(INVOKEINTERFACE, arg1, arg2, arg3);
    [javac]                           ^
    [javac] C:\Repositories\jython\src\org\python\modules\jffi\SkinnyMethodAdapter.java:843: warning: [deprecation] visitMethodInsn(int,String,String,String) in MethodVisitor has been deprecated
    [javac]     public void visitMethodInsn(int arg0, String arg1, String arg2, String arg3) {
    [javac]                 ^
    [javac] C:\Repositories\jython\src\org\python\modules\jffi\SkinnyMethodAdapter.java:844: warning: [deprecation] visitMethodInsn(int,String,String,String) in MethodVisitor has been deprecated
    [javac]         getMethodVisitor().visitMethodInsn(arg0, arg1, arg2, arg3);
    [javac]                           ^
    [javac] C:\Repositories\jython\src\org\python\modules\jffi\StructLayout.java:144: warning: [deprecation] Struct(Type...) in Struct has been deprecated
    [javac]                     : new com.kenai.jffi.Struct(fieldTypes);
    [javac]                       ^
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 8 warnings
    [javac] C:\Repositories\jython\build.xml:485: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] C:\Repositories\jython\build.xml:497: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 128 source files to C:\Repositories\jython\build\classes
    [javac] Note: C:\Repositories\jython\tests\java\javatests\DiamondIterableMapMRO.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
     [copy] Copying 1 file to C:\Repositories\jython\build\classes\org\python\modules
     [copy] Copying 1 file to C:\Repositories\jython\build\classes
     [copy] Copying 1 file to C:\Repositories\jython\build\classes\META-INF\services

expose:
   [expose] Exposing 227 classes

jar:
      [jar] Building jar: C:\Repositories\jython\dist\callbacker_test.jar
      [jar] Building jar: C:\Repositories\jython\dist\jython-dev.jar

copy-javalib:
     [copy] Copying 59 files to C:\Repositories\jython\dist\javalib

copy-cpythonlib:
     [copy] Copying 1130 files to C:\Repositories\jython\dist\Lib

copy-lib:
     [copy] Copying 535 files to C:\Repositories\jython\dist\Lib
     [copy] Copying 5 files to C:\Repositories\jython\dist\bin
     [copy] Copying 1 file to C:\Repositories\jython\dist

pycompile:
[jycompile] Compiling 643 files

developer-build:

BUILD SUCCESSFUL
Total time: 1 minute 15 seconds
````

**Comment by Stewori** [comment]
Hello Richard, please specify the actual error and how you started or used Jython. How do you see that it does not work? What binary are you referring to? jython.exe?
I think the build looks quite normal -- yes it ouputs some warnings but these are known. However IIRC running plain ``ant`` only creates jython-dev.jar. I'm not totally sure right now how that actually differs from usual jython.jar. It may be just suitable for use as a library. Better build by one of these commands:
``ant build``, ``ant jar-standalone`` or ``ant installer``. This should give you a proper build.

**Comment by jamesmudd** [comment]
To run the `jython-dev.jar` you need to pass it to Java. Try:
```
$ java -jar jython-dev.jar
```
You should get the interactive interpreter.

**Comment by RichardDally** [comment]
```
C:\Repositories\jython\dist>java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

C:\Repositories\jython\dist>java -jar jython-dev.jar
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/MapMaker
        at org.python.core.PyType$LazyClassToTypeHolder.<clinit>(PyType.java:2252)
        at org.python.core.PyType.getClassToType(PyType.java:2257)
        at org.python.core.PyType.fromClass(PyType.java:1540)
        at org.python.core.PyObject.<init>(PyObject.java:93)
        at org.python.core.PyBuiltinCallable.<init>(PyBuiltinCallable.java:22)
        at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:16)
        at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:21)
        at org.python.core.PyType$type___init___exposer.<init>(Unknown Source)
        at org.python.core.PyType$PyExposer.<init>(Unknown Source)
        at org.python.core.PyType.<clinit>(PyType.java)
        at org.python.core.PyObject.<init>(PyObject.java:93)
        at org.python.core.PyBuiltinCallable.<init>(PyBuiltinCallable.java:22)
        at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:16)
        at org.python.core.PyBuiltinMethodNarrow.<init>(PyBuiltinMethodNarrow.java:23)
        at org.python.core.PyDataDescr$getset_descriptor___get___exposer.<init>(Unknown Source)
        at org.python.core.PyDataDescr$PyExposer.<init>(Unknown Source)
        at org.python.core.PyDataDescr.<clinit>(PyDataDescr.java)
        at org.python.core.PyBuiltinCallable$PyExposer.<init>(Unknown Source)
        at org.python.core.PyBuiltinCallable.<clinit>(PyBuiltinCallable.java)
        at org.python.core.PyObject$PyExposer.<init>(Unknown Source)
        at org.python.core.PyObject.<clinit>(PyObject.java)
        at org.python.util.jython.run(jython.java:241)
        at org.python.util.jython.main(jython.java:142)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.MapMaker
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 23 more

C:\Repositories\jython\dist>
```

**Comment by Stewori** [comment]
> Compiling with JDK version X and using version Y could be a troublemaker ?

I think it would work to the extend that ordinary Java code would. If X > Y it can help to use the options ``-source`` and ``-target``. E.g. see https://github.com/Stewori/JyNI/blob/master/makefile#L64

Regarding ``java -jar jython-dev.jar`` I think it simply doesn't have its dependencies included. You would have to put various jars from the ``extlib`` folder on the classpath. And ``Lib`` on the pythonpath. I think ``ant build`` includes ``extlib`` in the jar (via jarjarlinks I suppose), that should be the difference between ``jython-dev.jar`` and ``jython.jar``. Standalone finally even includes ``Lib`` into the jar. Without this one has to distribute the Lib folder along with ``jython.jar`` and configure the pythonpath appropriately (the launcher, i.e. on Windows ``jython.exe``, usually takes care of this).

Disclaimer: I may have overlooked something. Haven't actually tried these things for a while.

**Comment by Stewori** [comment]
> Would it be possible to include several Python modules (such as mock, unittest2) within standalone JAR ?

For Java libs:
Look into ``build.xml``. Search e.g. for guava. It will show up at three places or so. Assert there is a corresponding jar-file in the extlibs folder. At each occurrence of e.g. guava, add the libs you desire to the list in the same manner. Make sure to put the right jar files into ``extlib``. Your custom build should then include these jars.

For Python-libs:
I'm nt sure right now, but it may be sufficient to simply add them to the Lib folder before building.

**Comment by Stewori** [comment]
Maybe this is also interesting for you: In [JyOpenGL](https://github.com/Stewori/JyOpenGL) I have a makefile that packages a Python module into a jar with prebuilt classes for Jython:
https://github.com/Stewori/JyOpenGL/blob/master/makefile

**Comment by jeff5** [comment]
I must admit, that build is noisier than I remember it, but Stefan is right: on 2.7.1 and Java 8 (and Windows), that's what I get too. (I probably only built 2.7.1 on Java 7.) 

In spite of the noise mine works when I run it the way I normally run it, in PoSH and from the checkout directory.
```
PS gh144> dist\bin\jython -V
Jython 2.7.1
PS gh144> dist\bin\jython
Jython 2.7.1 (, May 28 2019, 14:07:50)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_181
Type "help", "copyright", "credits" or "license" for more information.
>>> 6*7
42
>>> map( lambda x:x*x, range(10) )
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
>>> exit()
```
And mine blows up in the way reported too:
```
PS gh144> java -jar dist\jython-dev.jar
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/MapMaker
        at org.python.core.PyType$LazyClassToTypeHolder.<clinit>(PyType.java:2252)
        at org.python.core.PyType.getClassToType(PyType.java:2257)
        at org.python.core.PyType.fromClass(PyType.java:1540)
...
```
But that's not how we use the dev-JAR. Unlike the standalone JAR it does not bundle any of the dependencies. You need them on the class path. And remember the `-jar` option ignores the class path. A good way prototype your own launch command is to ask the jython command what it would do:
```
PS gh144> dist\bin\jython --print
"C:\Program Files\Java\jdk1.8.0_181\bin\java" -Xmx512m -Xss2560k -classpath dist\jython-dev.jar;dist\javalib\*;. -Dpython.home=dist -Dpython.executable=dist\bin\jython.exe -Dpython.launcher.uname=windows -Dpython.launcher.tty=true org.python.util.jython
```
Maybe not all of this is absolutely necessary in your case, but you get the idea.

However, the dev-JAR, as well as absolutely needing the class path, is only really there for our use in debugging. If you build or find an installer, and use it, you get an installed Jython where you can type:
```
PS 271-test> java -jar inst\jython.jar
Jython 2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_181
Type "help", "copyright", "credits" or "license" for more information.
>>> map( lambda x:x*x, range(10) )
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
>>> exit()
```
Or you can use the launcher. Now, I remember `pip` as buggy on Windows in 2.7.1, but I've been wrong about `pip` before. On cursory inspection it seems to work, but needs to be installed by hand:
```
PS 271-test> inst\bin\jython -m pip -h
 . . . \271-test\inst\bin\jython.exe: No module named pip
PS 271-test> inst\bin\jython -m ensurepip
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
PS 271-test> inst\bin\jython -m pip -h

Usage:
  pip <command> [options]
...
```

What Stefan says about customising the `ant` build and adding to `extlibs` seems right, if you want a single JAR, once the business about the dev-JAR is understood. Just please name it in some way that won't be confused with a standard Jython JAR. Generally though, I think people approach this through a command that launches as suggested above, only with more things on the class path.

**Comment by jeff5** [comment]
And as a footnote to this, if you really want to launch with `java` in the development environment, for example to run your own application that uses Jython objects (as in [chapter 10 of the Jython book](https://jython.readthedocs.io/en/latest/chapter10/#making-use-of-a-loosely-coupled-object-factory)), then this example will do it:
```
java -cp ".;dist\jython-dev.jar;dist\javalib\*" org.jython.book.Main
```

**Comment by RichardDally** [comment]
Thank you very much all of you. I've achieved to produce a jython-standalone.jar containing all my necessary Python and Java dependencies. I'm still wondering what JDK version match each tag of Jython (minimum version for 2.7.0 and 2.7.1 ?)

**Comment by Stewori** [comment]
Jython 2.7.x requires at least Java 7.

**Comment by RichardDally** [comment]
Thank you @Stewori !

**Comment by Stewori** [comment]
You may want to keep in mind that Jython 2.7.0 and 2.7.1 had some issues with Java 9+, especially because of illegal access to non-puplic fields and methods. 2.7.2 will vastly improve Java 9+ compatibility.
