### ISSUE TITLE
No-ascii Windows username import subprocess module failed

### ISSUE THREAD

**Issue by BillionsRichard** [jythontools/jython#147]
at com.kenai.jffi.Foreign.newLoadError(Foreign.java:72)
	at com.kenai.jffi.Foreign.access$300(Foreign.java:42)
	at com.kenai.jffi.Foreign$InValidInstanceHolder.getForeign(Foreign.java:98)
	at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
	at com.kenai.jffi.Library.openLibrary(Library.java:157)
	at com.kenai.jffi.Library.getCachedInstance(Library.java:131)
	at org.python.modules.jffi.DynamicLibrary.<init>(DynamicLibrary.java:26)
	at org.python.modules.jffi.jffi.dlopen(jffi.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: C:\Users\Sa?ol\AppData\Local\Temp\jffi946630297317024306.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:371)
	at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:258)
	at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:444)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.kenai.jffi.Init.load(Init.java:68)
	at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
	at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
	at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
	at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
	at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
	at com.kenai.jffi.Type.resolveSize(Type.java:155)

**Comment by BillionsRichard** [comment]
by debugging ,i the flowing code from com.kenai.jffi.internal.StubLoader#loadFromJar cause the issue:
    private static void loadFromJar() throws IOException, UnsatisfiedLinkError {
        InputStream is = getStubLibraryStream();
        FileOutputStream os = null;

        try {
            File dstFile = File.createTempFile("jffi", "." + dlExtension());
            dstFile.deleteOnExit();
            os = new FileOutputStream(dstFile);
            ReadableByteChannel srcChannel = Channels.newChannel(is);

            for(long pos = 0L; is.available() > 0; pos += os.getChannel().transferFrom(srcChannel, pos, (long)Math.max(4096, is.available()))) {
                ;
            }

            os.close();
            os = null;
            System.load(dstFile.getAbsolutePath());
            dstFile.delete();
        } catch (IOException var9) {
            throw new UnsatisfiedLinkError(var9.getMessage());
        } finally {
            if (os != null) {
                os.close();
            }

            is.close();
        }
    }

**Comment by BillionsRichard** [comment]
File.createTempFile has create the dll tmp file in System.getProperty("java.io.tmpdir") which catains the user name encoding with utf8; when  call System.lod() function, the file file is encoding with 'gbk', so the dll can't be found, causing an exception raised.

**Comment by jeff5** [comment]
I see you're on Windows, but would like to know what version of Jython you are using.

Thanks for isolating this to a file name problem. The handling of non-ascii file names, including those that result from user names, used to be poor. We have done a lot to improve it. Your problem is quite likely fixed, ready for version 2.7.2.

**Comment by BillionsRichard** [comment]
I'm using jython-standalone-2.7.1.patch2609.jar, and i found that it's not the jython code cause the issue, it's the com.kenai.jffi.internal.StubLoader does, depended by jython. the root cause is the defact of System.load() function can not handle no-ascii path param.
https://github.com/libgdx/libgdx/issues/5524

**Comment by jeff5** [comment]
From the name I suppose the JAR is one made privately.

Are you invoking this via the `ctypes` module? Have you a short script that would cause the error (if I log in as my non-ascii persona)?

Quite probably there is a confusion between bytes and characters in the way `org.python.modules.jffi` deals with the DLL file name. Thanks for finding this for us.

**Comment by BillionsRichard** [comment]
"import subprocess" in a python script, when compiling the script  on windows platform when you log in as your non-ascii username will trigger the issue.
By debugging, i found that it's the defact of the System.load() function which cannot handle the non-ascii parameters.

**Comment by jeff5** [comment]
We seem to have concluded it is not a Jython bug. jffi JARs have been upgraded in 2.7.2.
