### ISSUE TITLE
java.io.IOException: java.io.IOException: Resetting to invalid mark

### ISSUE THREAD

**Issue by cqzuo** [jythontools/jython#164]
I am using ast module to convert json string to dict object..
the size of json string about 170kb...
here is the code
import ast 
filename = '/home/workflow/python/20191211113037_MERGE_78328.json'
file = open(filename,'r+')
data =  file.read()
file.close() 
data_dict = ast.literal_eval(data.strip())

but it works well in python,I am using jython-standalone-2.5.3.jar or jython-standalone-2.7.0.jar has the same result.

the exception info :
java.io.IOException: Resetting to invalid mark
	at java.io.BufferedInputStream.reset(BufferedInputStream.java:448)
	at org.python.core.ParserFacade.readEncoding(ParserFacade.java:398)
	at org.python.core.ParserFacade.prepBufReader(ParserFacade.java:304)
	at org.python.core.ParserFacade.prepBufReader(ParserFacade.java:360)
	at org.python.core.ParserFacade.parse(ParserFacade.java:202)
	at org.python.core.CompileFunction.compile(__builtin__.java:1672)
	at org.python.core.CompileFunction.compile(__builtin__.java:1648)
	at org.python.core.CompileFunction.__call__(__builtin__.java:1636)
	at org.python.core.PyObject.__call__(PyObject.java:515)
	at org.python.core.PyObject.__call__(PyObject.java:521)
	at ast$py.parse$1(/home/zmc/zmc_home/server/lib/jython-standalone-2.7.0.jar/Lib/ast.py:37)
	at ast$py.call_function(/home/zmc/zmc_home/server/lib/jython-standalone-2.7.0.jar/Lib/ast.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyFunction.function___call__(PyFunction.java:471)
	at org.python.core.PyFunction.__call__(PyFunction.java:466)
	at ast$py.literal_eval$2(/home/zmc/zmc_home/server/lib/jython-standalone-2.7.0.jar/Lib/ast.py:80)
	at ast$py.call_function(/home/zmc/zmc_home/server/lib/jython-standalone-2.7.0.jar/Lib/ast.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)

**Comment by jeff5** [comment]
I think the offending bit of `ParserFacade.java` is that concerned with encoding declarations. It reads the first two lines looking for one, then backs up to re-read the stream (which here wraps your `str`) in the correct encoding. If the first two comprises more than100k bytes, it can fail to go back to the mark.

Is your data one enormous line by any chance? Just putting a couple of newlines at the front may be all it takes.

**Comment by cqzuo** [comment]
yes,my data is one enormous line.later, i am dealing the data with java ... and deal the json data one by one in python. a stupid method , ^-^

**Comment by jeff5** [comment]
So that fixes it for you?

Jython should deal with that or produce a better message, but I don't propose to fix that (for 2.7.2).

**Comment by cqzuo** [comment]
yes, It can be avoided in business code...
