### ISSUE TITLE
SSLError(1, u'Received fatal alert: internal_error') while requesting ssl pages

### ISSUE THREAD

**Issue by TBail** [jythontools/jython#165]
Hi there,

i am very new to jython and found an issue. My environemt in an raspberry pi 3 with DietPi v6.26.3. The java environment is aopenHAB instalaltion that uses

`openjdk version "1.8.0_222"
OpenJDK Runtime Environment (Zulu8.40.0.178-CA-linux_aarch32hf) (build 1.8.0_222-b178)
OpenJDK Client VM (Zulu8.40.0.178-CA-linux_aarch32hf) (build 25.222-b178, mixed mode, Evaluation)`

If i try to request a ssl webpage with the requests library i got the following error:

`Traceback (most recent call last):
  File "/etc/openhab2/automation/lib/python/core/log.py", line 51, in wrapper
    return fn(*args, **kwargs)
  File "<script>", line 19, in ReadIceWarning
  File "/etc/openhab2/automation/lib/python/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/etc/openhab2/automation/lib/python/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/etc/openhab2/automation/lib/python/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/etc/openhab2/automation/lib/python/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/etc/openhab2/automation/lib/python/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='api.eiswarnung.de', port=443): Max retries exceeded with url: /api/public/?lng=9.66561413531053&key=xxxxxxxxxxxxxx&lat=53.73338496170717 (Caused by SSLError(SSLError(1, u'Received fatal alert: internal_error'),))`

Unfortunately if i use the same request statements in pure python the request ist working well.

Maybe someone has a hint on that.

**Comment by lukicsl** [comment]
I have the same issue. I was not sure if this is introduced by the special usage of opehab.
I have created a docker container with standalone Jython (2.7.0, 2.7.1 and 2.7.2). there I get the same failure though with a better stack trace:

```
root@5ddd8c24f29b:/# python
Jython 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[OpenJDK Server VM (AdoptOpenJDK)] on java14
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> import json
>>> r =requests.get('http://api.eiswarnung.de/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/jython/Lib/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/jython/Lib/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/jython/Lib/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/jython/Lib/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/jython/Lib/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/local/jython/Lib/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/jython/Lib/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.eiswarnung.de', port=443): Max retries exceeded with url: /api/public/ (Caused by SSLError(SSLError(1, u'Received fatal alert: internal_error'),))
>>> 

```
Opened a ticket at request, seems not to be their issue:
https://github.com/psf/requests/issues/5423

**Comment by lukicsl** [comment]
the same issue is if using urllib3:
```
root@34b4e3a1e41b:/# python
Jython 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[OpenJDK Server VM (AdoptOpenJDK)] on java14
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>> http = urllib3.PoolManager()
>>> r = http.request('GET', 'http://api.eiswarnung.de/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/jython/Lib/site-packages/urllib3/request.py", line 75, in request
    return self.request_encode_url(
  File "/usr/local/jython/Lib/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/jython/Lib/site-packages/urllib3/poolmanager.py", line 369, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/usr/local/jython/Lib/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/jython/Lib/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/local/jython/Lib/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/local/jython/Lib/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/local/jython/Lib/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.eiswarnung.de', port=443): Max retries exceeded with url: /api/public/ (Caused by SSLError(SSLError(1, u'Received fatal alert: internal_error'),))
>>> 
```

**Comment by jeff5** [comment]
Originally raised as https://github.com/jythontools/jython issue 165.
