### ISSUE TITLE
ver2.7.2b2 java.lang.NullPointerException on PrePy.getEffectiveLoggingLevel

### ISSUE THREAD

**Issue by ocwvar** [jythontools/jython#167]
This issus happen when run on j2ee project. But it's total fine when i directly run the code.
It seems like every Jython code will cause this same issus.

**JYTHON VERSION:**
2.7.2b2   and   2.7.0
i havent try other version

**CODE:**
`Py.initPython();` 
or
 `Py.newString`

**LOG:**
`java.lang.NullPointerException
		at org.python.core.PrePy.getEffectiveLoggingLevel(PrePy.java:113)
		at org.python.core.PrePy.getLoggingLevel(PrePy.java:121)
		at org.python.core.Options.<clinit>(Options.java:83)
		at org.python.core.PyJavaType.isAccessibleClass(PyJavaType.java:656)
		at org.python.core.PyJavaType.init(PyJavaType.java:450)
		at org.python.core.PyType$Registry.createType(PyType.java:430)
		at org.python.core.PyType$Registry.addFromClass(PyType.java:379)
		at org.python.core.PyType$Registry.resolveType(PyType.java:296)
		at org.python.core.PyType$Registry$1.computeValue(PyType.java:210)
		at org.python.core.PyType$Registry$1.computeValue(PyType.java:204)
		at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:226)
		at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:208)
		at java.base/java.lang.ClassValue.get(ClassValue.java:114)
		at org.python.core.PyType.fromClass(PyType.java:2056)
		at org.python.core.PyJavaType$Constant.<clinit>(PyJavaType.java:96)
		at org.python.core.PyType$Registry.createType(PyType.java:417)
		at org.python.core.PyType$Registry.addFromClass(PyType.java:379)
		at org.python.core.PyType$Registry.resolveType(PyType.java:296)
		at org.python.core.PyType$Registry$1.computeValue(PyType.java:210)
		at org.python.core.PyType$Registry$1.computeValue(PyType.java:204)
		at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:226)
		at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:208)
		at java.base/java.lang.ClassValue.get(ClassValue.java:114)
		at org.python.core.PyType.fromClass(PyType.java:2056)
		at org.python.core.PyJavaType.<clinit>(PyJavaType.java:101)
		at org.python.core.PyType$Registry.createType(PyType.java:408)
		at org.python.core.PyType$Registry.addFromClass(PyType.java:379)
		at org.python.core.PyType$Registry.resolveType(PyType.java:313)
		at org.python.core.PyType$Registry$1.computeValue(PyType.java:210)
		at org.python.core.PyType$Registry$1.computeValue(PyType.java:204)
		at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:226)
		at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:208)
		at java.base/java.lang.ClassValue.get(ClassValue.java:114)
		at org.python.core.PyType.fromClass(PyType.java:2056)
		at org.python.core.PyObject.<init>(PyObject.java:85)
		at org.python.core.PySingleton.<init>(PySingleton.java:9)
		at org.python.core.PyNotImplemented.<init>(PyNotImplemented.java:10)
		at org.python.core.Py.<clinit>(Py.java:66)`

this crash log seems like "Logger" is NULL, when run on:
`while((level = logger.getLevel()) == null)`

but i output that logger outside like this:
`System.out.println(Logger.getLogger( "org.python" ))`
it shows not null

**Comment by ocwvar** [comment]
**directly run the code**  means not deploy on server but just run on **main()**

sorry for my poor english

**Comment by jeff5** [comment]
Your English is quite understandable. Thanks for trying the beta.

I believe the problem you observe is fixed here (as a result of issue [2844](https://bugs.jython.org/issue2844)): https://github.com/jythontools/jython/commit/ce13c0d726aee1a094608167b6934c9696f1414f. The relevant part is the change to ``getEffectiveLoggingLevel`. It happens when no logging level is explicitly set at any level of the hierarchy.

There will be a beta 3 with this fix to try in a few weeks.

**Comment by ocwvar** [comment]
thanks, can’t wait to try ;)

**Comment by ocwvar** [comment]
I just build a beta3 version, and testing seems ok. :D

**Builded Version**
`2.7.2b3-SNAPSHOT (uncontrolled:+, 1?? 30 2020, 15:18:27)`
