### ISSUE TITLE
I used JPython2.7.2 and it throw this : java.lang.IllegalArgumentException: URI is not hierarchical when I package Project

### ISSUE THREAD

**Issue by Peng0529** [jythontools/jython#178]
log:
```
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(Unknown Source) ~[na:1.8.0_202]
	at org.python.core.PrePy.getJarFileNameFromURL(PrePy.java:427) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.core.PrePy._getJarFileName(PrePy.java:362) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.core.PrePy.getJarFileName(PrePy.java:345) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.core.PySystemState.doInitialize(PySystemState.java:1195) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.core.PySystemState.initialize(PySystemState.java:1130) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.core.PySystemState.initialize(PySystemState.java:1085) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.core.PySystemState.initialize(PySystemState.java:1080) ~[jython-2.7.2.jar!/:2.7.2]
	at org.python.util.PythonInterpreter.initialize(PythonInterpreter.java:63) ~[jython-2.7.2.jar!/:2.7.2]
```
code:
```
        Properties props = new Properties();
        props.put("python.security.respectJavaAccessibility", "false"); 
        props.put("python.import.site","false");
        Properties preprops = System.getProperties();
        PythonInterpreter.initialize(preprops, props, new String[0]);
        PythonInterpreter interpreter = new PythonInterpreter();  //Here is the trigger point
        interpreter.exec("import math");
        interpreter.exec("import sys");
```
I hope to get help, how do I use it

**Comment by jeff5** [comment]
There seems to be a problem when the Jython JAR is embedded in another JAR: the way in which we locate our JAR does not take into account this possible nesting of JARs.

Changes to clean up this bit of code pass tests, but these tests don't include the sort of paths that appear when the JAR is nested. An example of such a path from your application would be useful to help put this right in a future bugfix release.

Correlates with https://bugs.jython.org/issue2870, https://bugs.jython.org/issue2876 .

A work-around might be to explode our JAR into your own, so that there is only one level between you application and our classes, or otherwise have it the Jython on the path of your application (not nested).
