### ISSUE TITLE
java.lang.RuntimeException: java.lang.RuntimeException: Method code too large!

### ISSUE THREAD

**Issue by rakeshbabuseva** [jythontools/jython#46]
**jython version  = 2.7.0
I was trying to install the dropbox module using the below command

jython(set in path variable) setup.py(dropbox setup.py) install**

_**below are the error details**_
_C:\jython2.7.0\Lib\distutils\dist.py", line 972, in run_command
   cmd_obj.run()
 File "C:\jython2.7.0\Lib\site-packages\setuptools-3.1-py2.7.egg\setuptools\command\install.py", line 74, in run
 File "C:\jython2.7.0\Lib\site-packages\setuptools-3.1-py2.7.egg\setuptools\command\install.py", line 89, in do_egg_install
 File "C:\jython2.7.0\Lib\distutils\cmd.py", line 326, in run_command
   self.distribution.run_command(command)
 File "C:\jython2.7.0\Lib\distutils\dist.py", line 972, in run_command
   cmd_obj.run()
 File "C:\jython2.7.0\Lib\site-packages\setuptools-3.1-py2.7.egg\setuptools\command\bdist_egg.py", line 185, in run
 File "C:\jython2.7.0\Lib\site-packages\setuptools-3.1-py2.7.egg\setuptools\command\bdist_egg.py", line 171, in call_command
 File "C:\jython2.7.0\Lib\distutils\cmd.py", line 326, in run_command
   self.distribution.run_command(command)
 File "C:\jython2.7.0\Lib\distutils\dist.py", line 972, in run_command
   cmd_obj.run()
 File "C:\jython2.7.0\Lib\site-packages\setuptools-3.1-py2.7.egg\setuptools\command\install_lib.py", line 12, in run
 File "C:\jython2.7.0\Lib\distutils\command\install_lib.py", line 136, in byte_compile
   byte_compile(files, optimize=0,
 File "C:\jython2.7.0\Lib\distutils\util.py", line 567, in byte_compile
   compile(file, cfile, dfile)
 File "C:\jython2.7.0\Lib\py_compile.py", line 96, in compile
   _py_compile.compile(file, cfile, dfile)
 File "C:\jython2.7.0\Lib\py_compile.py", line 96, in compile
   _py_compile.compile(file, cfile, dfile)
       at org.python.objectweb.asm.MethodWriter.a(Unknown Source)
       at org.python.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
       at org.python.compiler.ClassFile.write(ClassFile.java:215)
       at org.python.compiler.Module.write(Module.java:620)
       at org.python.compiler.Module.compile(Module.java:676)
       at org.python.core.imp.compileSource(imp.java:370)
       at org.python.core.imp.compileSource(imp.java:292)
       at org.python.modules._py_compile.compile(_py_compile.java:28)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:606)

java.lang.RuntimeException: java.lang.RuntimeException: Method code too large!_

Is there any solution for this issue other than breaking the code into small chunks as referred in http://bugs.jython.org/issue1891, Since I may not able to change the third-party modules all the time

**Comment by Stewori** [comment]
No solution yet. Just a small hint to make it less painful. Whenever you fix a module this way, please consider to make it available publicly. If you can host the fixed variant as a fork of the original module (e.g. here on github), in most cases the merging algorithm can merge future updates automatically.

Usually I would recommend to make a PR to the original module, if splitting the method yields no regression. However mostly such oversized methods arise in generated code, which can make a permanent fix overly complicated (needing to put hands on the generator). So using the merge algorithm is maybe the easiest way to permanently maintain the fix with hardly any additional effort.

**Comment by Stewori** [comment]
As of https://github.com/jythontools/jython/commit/2c0dda9be0b7bb9f094960a251cbe93c1dd170aa I could improve this issue a lot. It should work now if you put a CPython 2.7 bytecode .pyc file of the affected module into its folder, e.g. by `python -m py_compile filename.py`
It would be great if you could confirm this solution or share here the results whatsoever.

**Comment by Stewori** [comment]
This kind of issue is now fairly workable by providing a CPython bytecode file (.pyc) for the affected module, so closing it.
For further discussion stick to http://bugs.jython.org/issue527524
